#!/usr/bin/env python3

import lib
# import pprint
# import sys
# import json

lib.do_check()

# check_input_payload = lib.read_input()

# pprint.pprint(check_input_payload, stream=sys.stderr)

# print(json.dumps([{}]))

# check = new lib.check()

# check.init()
