#!/usr/bin/env python3

import lib.common
import lib.root_ca


# =============================================================================
#
# general
#
# =============================================================================

# =============================================================================
# do_in
# =============================================================================
def do_in() -> None:
    # read the concourse input payload from stdin
    input_config = lib.common.read_concourse_input_payload()

# read input payload from stdin
# first argument ($1) contains destination directory

# check s3 for keys
# check the checksums in s3
# calculate combined checksum
# if combined checksum matces, download copies locally
# if they don't match, throw an error (version not found)
